 version: '3.3'
 services:
   service:
     tty: true
     image: node:14.16.0
     volumes:
       - '.:/code'
     working_dir: /code
     command: >
       sh -c  "yarn install && yarn build"
     depends_on:
       - nginx_server
   nginx_server:
     image: 'nginx:latest'
     volumes:
       - './build:/usr/share/nginx/html'
       - './nginx_conf_docker/default.conf:/etc/nginx/conf.d/default.conf'
     ports:
       - '8006:80'
     restart: always
